services:
  rabbitmq:
    image: rabbitmq:management
    hostname: template-rabbitmq
    ports:
      - 5672:5672
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: Kern-vull-friw